version: "3.0"
services:
  nginx:
    ports:
      - "80:80"
  node-docker-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENVIRONMENT=production
    command: node index.js