version: "3.0"
services:
  nginx:
    ports:
      - "3000:80"
  node-docker-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENVIRONMENT=development
      - MONGO_USER=ed
      - MONGO_PASSWORD=password
      - SESSION_SECRET=random-string
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ed
      - MONGO_INITDB_ROOT_PASSWORD=password
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24