version: "3.0"
services:
  node-docker-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=4000
    env_file:
      - ./.env
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24