version: "3.0"
services:
  nginx:
    ports:
      - "3000:80"
  node-docker-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENVIRONMENT=development
    command: npm run dev